#assets
public/assets/

#silverstripe
public/cms/
public/framework/

#modules
public/betterbuttons/
public/gridfieldextensions/
public/gridfield-bulk-editing-tools/
public/versioned-gridfield/

#dev stuff
_ss_environment.php
.idea/
.vagrant/
build-scripts/node_modules/
build-scripts/bower_components/
db/
logs/
.sass-cache/
public/vendor/
vagrant-config/
puphpet/
/vendor/
/composer.json
/composer.lock

